package com.retropoktan.lshousekeeping.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig superItemDaoConfig;

    private final SuperItemDao superItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        superItemDaoConfig = daoConfigMap.get(SuperItemDao.class).clone();
        superItemDaoConfig.initIdentityScope(type);

        superItemDao = new SuperItemDao(superItemDaoConfig, this);

        registerDao(SuperItem.class, superItemDao);
    }
    
    public void clear() {
        superItemDaoConfig.getIdentityScope().clear();
    }

    public SuperItemDao getSuperItemDao() {
        return superItemDao;
    }

}
